version: "3.9"
services:
  custom-mongodb-exporter:
    build: .
    ports:
      - "8890:8890"
    environment:
      - MONGODB_URI=mongodb://user:password@host:27017
      - DATABASE_NAME=database_name
      - COLLECTIONS="profiles, events"
